### ISSUE TITLE
No code demo

### ISSUE THREAD

**Issue by Celiian** [chad-autry/hex-widget#54]
Simple to understand when we want to see the source code of the demo it tells us the route doesn't exist (it does the same in the 3D version)

**Comment by chad-autry** [comment]
All the links I checked seemed fine. Which one is giving you a problem?

**Comment by Celiian** [comment]
https://github.com/chad-autry/hex-grid-map/blob/master/gh-pages/src/app/demo/demo.js this link, on the read me when i want to acces the code of the demo i don't find a page

**Comment by Celiian** [comment]
And i also wanted to ask is your library easy to use in vue js ?

**Comment by chad-autry** [comment]
Ah, updated the link.
No experience or opinion on vue, the demo app is react and is what I've continued to use for my own project.
